import type { WorkoutDay } from "../workout";

export const mensBeginnerWorkoutDays: WorkoutDay[] = [
  // ======================
  // DAY 1 – Upper Body (Push + Pull)
  // ======================
  {
    day: "Day 1",
    variations: "Upper Body (Push + Pull)",
    exercises: [
      {
        id: "b1-1",
        name: "Lat Pulldown",
        equipment: "Cable / Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Pull elbows down, chest tall.",
      },
      {
        id: "b1-2",
        name: "Chest Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Controlled negative, no lockout slam.",
      },
      {
        id: "b1-3",
        name: "Seated Cable Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Neutral spine, pull with elbows.",
      },
      {
        id: "b1-4",
        name: "Pec Deck Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Light weight, stretch and squeeze.",
      },
      {
        id: "b1-5",
        name: "Dumbbell Lateral Raise",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Slight bend, raise to shoulder height.",
      },
      {
        id: "b1-6",
        name: "Cable Triceps Pushdown",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Elbows pinned to sides.",
      },
      {
        id: "b1-7",
        name: "Dumbbell Curl",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "No swinging, slow tempo.",
      },
    ],
  },

  // ======================
  // DAY 2 – Lower Body
  // ======================
  {
    day: "Day 2",
    variations: "Lower Body",
    exercises: [
      {
        id: "b2-1",
        name: "Leg Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Feet shoulder-width, controlled depth.",
      },
      {
        id: "b2-2",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Pause 1 sec at contraction.",
      },
      {
        id: "b2-3",
        name: "Goblet Squat",
        equipment: "Dumbbell",
        setType: "Straight",
        sets: 3,
        reps: "10",
        rest: 90,
        notes: "Chest upright, sit between hips.",
      },
      {
        id: "b2-4",
        name: "Walking Lunges",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "8 / leg",
        rest: 120,
        notes: "Short stride, balance first.",
      },
      {
        id: "b2-5",
        name: "Leg Extension",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Slow negative, no swinging.",
      },
      {
        id: "b2-6",
        name: "Standing Calf Raise",
        equipment: "Bodyweight / Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Full stretch and squeeze.",
      },
    ],
  },

  // ======================
  // DAY 3 – Upper Body (Back + Shoulders)
  // ======================
  {
    day: "Day 3",
    variations: "Upper Body (Back + Shoulders)",
    exercises: [
      {
        id: "b3-1",
        name: "Assisted Pull-Up / Pulldown",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Full stretch at top.",
      },
      {
        id: "b3-2",
        name: "Chest-Supported Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Neutral spine, controlled.",
      },
      {
        id: "b3-3",
        name: "Shoulder Press",
        equipment: "Machine / Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Stop 1–2 reps before failure.",
      },
      {
        id: "b3-4",
        name: "Seated Lateral Raise",
        equipment: "Machine / Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Light weight, strict form.",
      },
      {
        id: "b3-5",
        name: "Face Pull",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15",
        rest: 60,
        notes: "Rear delts and shoulder health.",
      },
      {
        id: "b3-6",
        name: "EZ-Bar Curl",
        equipment: "Barbell",
        setType: "Straight",
        sets: 2,
        reps: "12",
        rest: 60,
        notes: "Controlled tempo.",
      },
      {
        id: "b3-7",
        name: "Rope Triceps Extension",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "12",
        rest: 60,
        notes: "Full range of motion.",
      },
    ],
  },

  // ======================
  // DAY 4 – Lower Body + Core
  // ======================
  {
    day: "Day 4",
    variations: "Lower Body + Core",
    exercises: [
      {
        id: "b4-1",
        name: "Hack Squat / Leg Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 150,
        notes: "Controlled depth.",
      },
      {
        id: "b4-2",
        name: "Romanian Deadlift (DB)",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "10",
        rest: 120,
        notes: "Feel hamstring stretch.",
      },
      {
        id: "b4-3",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 90,
        notes: "Slow tempo.",
      },
      {
        id: "b4-4",
        name: "Hip Abduction",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "15",
        rest: 60,
        notes: "Controlled movement.",
      },
      {
        id: "b4-5",
        name: "Plank",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "30–45 sec",
        rest: 60,
        notes: "Neutral spine.",
      },
      {
        id: "b4-6",
        name: "Knee Raises (Bench / Hanging)",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Controlled reps, no swinging.",
      },
    ],
  },
];

export const mensIntermediateWorkoutDays: WorkoutDay[] = [
  {
    day: "Day 1",
    variations: "Back / Traps / Rear Delts + Triceps",
    exercises: [
      {
        id: "d1-1",
        name: "Lat Pullover",
        equipment: "Machine / Cable",
        setType: "Straight",
        sets: 2,
        reps: "10",
        rest: 60,
        notes:
          "Not to failure. Drive with elbows, bar to belly button. Blood flow & MMC focus.",
      },
      {
        id: "d1-2",
        name: "Chest-Supported T-Bar Row",
        equipment: "Machine",
        setType: "Triple Cluster",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes:
          "First 2 sets at working weight. Last set: triple cluster of 5 reps.",
      },
      {
        id: "d1-3",
        name: "Cable Pulldown (Pro Lat Bar)",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "10–15",
        rest: 120,
        notes:
          "Torso upright, elbows tucked forward, do not lean back excessively.",
      },
      {
        id: "d1-4",
        name: "Reverse Grip High Row",
        equipment: "Plate-Loaded Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–15",
        rest: 120,
        notes: "One arm at a time. Align shoulder with handle, drive to hip.",
      },
      {
        id: "d1-5",
        name: "Smith Machine Shrug",
        equipment: "Smith Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 90,
        notes: "Slight forward lean, arms slightly forward. Controlled tempo.",
      },
      {
        id: "d1-6",
        name: "Reverse Pec Deck Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 90,
        notes: "Light weight, partial ROM. Do not retract scapula excessively.",
      },
      {
        id: "d1-7",
        name: "Cable Rope Triceps Pushdown",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Elbows pinned, full lockout, slow negatives.",
      },
    ],
  },

  {
    day: "Day 2",
    variations: "Chest / Side Delts + Biceps",
    exercises: [
      {
        id: "d2-1",
        name: "Seated Pec Deck Chest Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "15",
        rest: 60,
        notes: "Chest up, shoulders tucked back. Pump-focused.",
      },
      {
        id: "d2-2",
        name: "Incline Plate-Loaded Chest Press",
        equipment: "Machine",
        setType: "Back-Off Cluster",
        sets: 2,
        reps: "8–12",
        rest: 120,
        notes: "Top set followed by back-off cluster: 25% less, 6×3.",
      },
      {
        id: "d2-3",
        name: "Smith Machine Incline Bench Press",
        equipment: "Smith Machine",
        setType: "Straight",
        sets: 2,
        reps: "8–10",
        rest: 120,
        notes: "Top set followed by back-off of 12–15 reps at 25% less.",
      },
      {
        id: "d2-4",
        name: "Flat Plate-Loaded Chest Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Controlled straight sets.",
      },
      {
        id: "d2-5",
        name: "Seated Lateral Raise",
        equipment: "Machine",
        setType: "Triple Cluster",
        sets: 3,
        reps: "18",
        rest: 90,
        notes: "6×3 cluster, arms slightly forward.",
      },
      {
        id: "d2-6",
        name: "Dumbbell Lateral Raise",
        equipment: "Dumbbells",
        setType: "Run the Rack",
        sets: 2,
        reps: "8–15",
        rest: 90,
        notes: "Drop weight every mini-set.",
      },
      {
        id: "d2-7",
        name: "Incline Dumbbell Curl",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Stretch-focused, no swinging.",
      },
    ],
  },

  {
    day: "Day 3",
    variations: "Legs + Triceps",
    exercises: [
      {
        id: "d3-1",
        name: "Seated Hip Abduction",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12",
        rest: 90,
        notes: "Superset with adductors.",
      },
      {
        id: "d3-2",
        name: "Seated Adductor",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12",
        rest: 90,
        notes: "Superset with abductors.",
      },
      {
        id: "d3-3",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes: "Controlled tempo.",
      },
      {
        id: "d3-4",
        name: "Hack Squat",
        equipment: "Machine",
        setType: "Top + Back-Off",
        sets: 2,
        reps: "8–12",
        rest: 180,
        notes: "Top set followed by back-off at 25% less.",
      },
      {
        id: "d3-5",
        name: "Incline Leg Press (Single Leg)",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 180,
        notes: "Quad-focused.",
      },
      {
        id: "d3-6",
        name: "Leg Extension",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "8–12",
        rest: 120,
        notes: "No swinging.",
      },
      {
        id: "d3-7",
        name: "DB Walking Lunges",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "10 / leg",
        rest: 180,
        notes: "Long stride.",
      },
      {
        id: "d3-8",
        name: "Overhead Cable Triceps Extension",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Long-head emphasis.",
      },
    ],
  },

  {
    day: "Day 4",
    variations: "Abs",
    exercises: [
      {
        id: "d4-1",
        name: "Decline Bench Reverse Crunch",
        equipment: "Bench",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
      {
        id: "d4-2",
        name: "90° Hyperextension Sit-Up",
        equipment: "Hyperextension Bench",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
      {
        id: "d4-3",
        name: "Seated Crunch Machine",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
    ],
  },

  {
    day: "Day 5",
    variations: "Back / Chest + Biceps",
    exercises: [
      {
        id: "d5-1",
        name: "Plate-Loaded Low Row",
        equipment: "Machine",
        setType: "Drop Set",
        sets: 2,
        reps: "8–12",
        rest: 180,
        notes: "Top set → back-off → drop to failure.",
      },
      {
        id: "d5-2",
        name: "Single-Arm Cable Lat Pulldown",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes: "Drive to hip.",
      },
      {
        id: "d5-3",
        name: "Seated Cable Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes: "Chest tall.",
      },
      {
        id: "d5-4",
        name: "Cable Seated Chest Press",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 120,
        notes: "Downward path.",
      },
      {
        id: "d5-5",
        name: "Dumbbell Incline Bench Press",
        equipment: "Dumbbells",
        setType: "Cluster Back-Off",
        sets: 2,
        reps: "8–10",
        rest: 180,
        notes: "6×3 cluster.",
      },
      {
        id: "d5-6",
        name: "Lying Plate-Loaded Chest Press",
        equipment: "Machine",
        setType: "Top + Back-Off",
        sets: 3,
        reps: "8–10",
        rest: 180,
        notes: "2 top sets, 1 back-off.",
      },
      {
        id: "d5-7",
        name: "Cable Preacher Curl",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Peak squeeze.",
      },
    ],
  },

  {
    day: "Day 6",
    variations: "Shoulders / Triceps / Biceps",
    exercises: [
      {
        id: "d6-1",
        name: "Seated Lateral Raise",
        equipment: "Machine",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 120,
        notes: "Last set double drop.",
      },
      {
        id: "d6-2",
        name: "Plate-Loaded Shoulder Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "8–10",
        rest: 180,
        notes: "",
      },
      {
        id: "d6-3",
        name: "Seated DB Lateral Raise",
        equipment: "Dumbbells",
        setType: "Drop Set",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Drop 25% each set.",
      },
      {
        id: "d6-4",
        name: "Cable One-Arm Lateral Raise",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 120,
        notes: "Pinkies up.",
      },
      {
        id: "d6-5",
        name: "Standing Cable Rear Delt Fly",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "15–20",
        rest: 120,
        notes: "Partial ROM.",
      },
      {
        id: "d6-6",
        name: "Lying Triceps Extension (Skull Crushers)",
        equipment: "EZ Bar",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "",
      },
      {
        id: "d6-7",
        name: "Biceps Curl (21s)",
        equipment: "Barbell / Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "21",
        rest: 120,
        notes: "7 bottom, 7 top, 7 full.",
      },
    ],
  },

  {
    day: "Day 7",
    variations: "Abs",
    exercises: [
      {
        id: "d7-1",
        name: "Decline Bench Reverse Crunch",
        equipment: "Bench",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
      {
        id: "d7-2",
        name: "90° Hyperextension Sit-Up",
        equipment: "Hyperextension Bench",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
      {
        id: "d7-3",
        name: "Seated Crunch Machine",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
    ],
  },
];

export const womensBeginnerWorkoutDays: WorkoutDay[] = [
  {
    day: "Day 1",
    variations: "Glutes and Hams",
    exercises: [
      {
        id: "b1-1",
        name: "Lat Pulldown",
        equipment: "Cable / Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Pull elbows down, chest tall.",
      },
    ],
  },
];

export const womensIntermediateWorkoutDays: WorkoutDay[] = [
  {
    day: "Day 1",
    variations: "Quads and Arms",
    exercises: [
      {
        id: "b1-1",
        name: "Lat Pulldown",
        equipment: "Cable / Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Pull elbows down, chest tall.",
      },
    ],
  },
];
