import type { WorkoutDay } from "../workout";

export const mensBeginnerWorkoutDays: WorkoutDay[] = [
  // ======================
  // DAY 1 – Upper Body (Push + Pull)
  // ======================
  {
    day: "Day 1",
    variations: "Upper Body (Push + Pull)",
    link: "https://link.strong.app/awxpazgn",
    exercises: [
      {
        id: "b1-1",
        name: "Lat Pulldown",
        equipment: "Cable / Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Pull elbows down, chest tall.",
      },
      {
        id: "b1-2",
        name: "Chest Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Controlled negative, no lockout slam.",
      },
      {
        id: "b1-3",
        name: "Seated Cable Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Neutral spine, pull with elbows.",
      },
      {
        id: "b1-4",
        name: "Pec Deck Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Light weight, stretch and squeeze.",
      },
      {
        id: "b1-5",
        name: "Dumbbell Lateral Raise",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Slight bend, raise to shoulder height.",
      },
      {
        id: "b1-6",
        name: "Cable Triceps Pushdown",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Elbows pinned to sides.",
      },
      {
        id: "b1-7",
        name: "Dumbbell Curl",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "No swinging, slow tempo.",
      },
    ],
  },

  // ======================
  // DAY 2 – Lower Body
  // ======================
  {
    day: "Day 2",
    variations: "Lower Body",
    link: "https://link.strong.app/vktvhbej",
    exercises: [
      {
        id: "b2-1",
        name: "Leg Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Feet shoulder-width, controlled depth.",
      },
      {
        id: "b2-2",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Pause 1 sec at contraction.",
      },
      {
        id: "b2-3",
        name: "Goblet Squat",
        equipment: "Dumbbell",
        setType: "Straight",
        sets: 3,
        reps: "10",
        rest: 90,
        notes: "Chest upright, sit between hips.",
      },
      {
        id: "b2-4",
        name: "Walking Lunges",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "8 / leg",
        rest: 120,
        notes: "Short stride, balance first.",
      },
      {
        id: "b2-5",
        name: "Leg Extension",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Slow negative, no swinging.",
      },
      {
        id: "b2-6",
        name: "Standing Calf Raise",
        equipment: "Bodyweight / Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Full stretch and squeeze.",
      },
    ],
  },

  // ======================
  // DAY 3 – Upper Body (Back + Shoulders)
  // ======================
  {
    day: "Day 3",
    variations: "Upper Body (Back + Shoulders)",
    link: "https://link.strong.app/mgwxwmha",
    exercises: [
      {
        id: "b3-1",
        name: "Assisted Pull-Up / Pulldown",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Full stretch at top.",
      },
      {
        id: "b3-2",
        name: "Chest-Supported Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Neutral spine, controlled.",
      },
      {
        id: "b3-3",
        name: "Shoulder Press",
        equipment: "Machine / Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Stop 1–2 reps before failure.",
      },
      {
        id: "b3-4",
        name: "Seated Lateral Raise",
        equipment: "Machine / Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Light weight, strict form.",
      },
      {
        id: "b3-5",
        name: "Face Pull",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15",
        rest: 60,
        notes: "Rear delts and shoulder health.",
      },
      {
        id: "b3-6",
        name: "EZ-Bar Curl",
        equipment: "Barbell",
        setType: "Straight",
        sets: 2,
        reps: "12",
        rest: 60,
        notes: "Controlled tempo.",
      },
      {
        id: "b3-7",
        name: "Rope Triceps Extension",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "12",
        rest: 60,
        notes: "Full range of motion.",
      },
    ],
  },

  // ======================
  // DAY 4 – Lower Body + Core
  // ======================
  {
    day: "Day 4",
    variations: "Lower Body + Core",
    link: "https://link.strong.app/ckfulcgr",
    exercises: [
      {
        id: "b4-1",
        name: "Hack Squat / Leg Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 150,
        notes: "Controlled depth.",
      },
      {
        id: "b4-2",
        name: "Romanian Deadlift (DB)",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "10",
        rest: 120,
        notes: "Feel hamstring stretch.",
      },
      {
        id: "b4-3",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 90,
        notes: "Slow tempo.",
      },
      {
        id: "b4-4",
        name: "Hip Abduction",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "15",
        rest: 60,
        notes: "Controlled movement.",
      },
      {
        id: "b4-5",
        name: "Plank",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "30–45 sec",
        rest: 60,
        notes: "Neutral spine.",
      },
      {
        id: "b4-6",
        name: "Knee Raises (Bench / Hanging)",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Controlled reps, no swinging.",
      },
    ],
  },
];

export const mensIntermediateWorkoutDays: WorkoutDay[] = [
  {
    day: "Day 1",
    variations: "Back / Traps / Rear Delts + Triceps",
    exercises: [
      {
        id: "d1-1",
        name: "Lat Pullover",
        equipment: "Machine / Cable",
        setType: "Straight",
        sets: 2,
        reps: "10",
        rest: 60,
        notes:
          "Not to failure. Drive with elbows, bar to belly button. Blood flow & MMC focus.",
      },
      {
        id: "d1-2",
        name: "Chest-Supported T-Bar Row",
        equipment: "Machine",
        setType: "Triple Cluster",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes:
          "First 2 sets at working weight. Last set: triple cluster of 5 reps.",
      },
      {
        id: "d1-3",
        name: "Cable Pulldown (Pro Lat Bar)",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "10–15",
        rest: 120,
        notes:
          "Torso upright, elbows tucked forward, do not lean back excessively.",
      },
      {
        id: "d1-4",
        name: "Reverse Grip High Row",
        equipment: "Plate-Loaded Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–15",
        rest: 120,
        notes: "One arm at a time. Align shoulder with handle, drive to hip.",
      },
      {
        id: "d1-5",
        name: "Smith Machine Shrug",
        equipment: "Smith Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 90,
        notes: "Slight forward lean, arms slightly forward. Controlled tempo.",
      },
      {
        id: "d1-6",
        name: "Reverse Pec Deck Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 90,
        notes: "Light weight, partial ROM. Do not retract scapula excessively.",
      },
      {
        id: "d1-7",
        name: "Cable Rope Triceps Pushdown",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Elbows pinned, full lockout, slow negatives.",
      },
    ],
  },

  {
    day: "Day 2",
    variations: "Chest / Side Delts + Biceps",
    exercises: [
      {
        id: "d2-1",
        name: "Seated Pec Deck Chest Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "15",
        rest: 60,
        notes: "Chest up, shoulders tucked back. Pump-focused.",
      },
      {
        id: "d2-2",
        name: "Incline Plate-Loaded Chest Press",
        equipment: "Machine",
        setType: "Back-Off Cluster",
        sets: 2,
        reps: "8–12",
        rest: 120,
        notes: "Top set followed by back-off cluster: 25% less, 6×3.",
      },
      {
        id: "d2-3",
        name: "Smith Machine Incline Bench Press",
        equipment: "Smith Machine",
        setType: "Straight",
        sets: 2,
        reps: "8–10",
        rest: 120,
        notes: "Top set followed by back-off of 12–15 reps at 25% less.",
      },
      {
        id: "d2-4",
        name: "Flat Plate-Loaded Chest Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Controlled straight sets.",
      },
      {
        id: "d2-5",
        name: "Seated Lateral Raise",
        equipment: "Machine",
        setType: "Triple Cluster",
        sets: 3,
        reps: "18",
        rest: 90,
        notes: "6×3 cluster, arms slightly forward.",
      },
      {
        id: "d2-6",
        name: "Dumbbell Lateral Raise",
        equipment: "Dumbbells",
        setType: "Run the Rack",
        sets: 2,
        reps: "8–15",
        rest: 90,
        notes: "Drop weight every mini-set.",
      },
      {
        id: "d2-7",
        name: "Incline Dumbbell Curl",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Stretch-focused, no swinging.",
      },
    ],
  },

  {
    day: "Day 3",
    variations: "Legs + Triceps",
    exercises: [
      {
        id: "d3-1",
        name: "Seated Hip Abduction",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12",
        rest: 90,
        notes: "Superset with adductors.",
      },
      {
        id: "d3-2",
        name: "Seated Adductor",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12",
        rest: 90,
        notes: "Superset with abductors.",
      },
      {
        id: "d3-3",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes: "Controlled tempo.",
      },
      {
        id: "d3-4",
        name: "Hack Squat",
        equipment: "Machine",
        setType: "Top + Back-Off",
        sets: 2,
        reps: "8–12",
        rest: 180,
        notes: "Top set followed by back-off at 25% less.",
      },
      {
        id: "d3-5",
        name: "Incline Leg Press (Single Leg)",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 180,
        notes: "Quad-focused.",
      },
      {
        id: "d3-6",
        name: "Leg Extension",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "8–12",
        rest: 120,
        notes: "No swinging.",
      },
      {
        id: "d3-7",
        name: "DB Walking Lunges",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "10 / leg",
        rest: 180,
        notes: "Long stride.",
      },
      {
        id: "d3-8",
        name: "Overhead Cable Triceps Extension",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Long-head emphasis.",
      },
    ],
  },

  {
    day: "Day 4",
    variations: "Abdominal Routine X Cardio",
    exercises: [
      {
        id: "d4-1",
        name: "Hanging Knee Raise",
        equipment: "Machine/ Free Hang",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "Engage your lower abs",
      },
      {
        id: "d4-2",
        name: "Wood Choppers",
        equipment: "Cable Station",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "Engage your obliques",
      },
      {
        id: "d4-3",
        name: "Rope Crunch",
        equipment: "Cable Statio",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Engage your mid section",
      },
      {
        id: "d4-4",
        name: "Incline Walk",
        equipment: "treadmill",
        setType: "steady State",
        sets: "30 mins",
        reps: "_",
        rest: 0,
        notes: "Speed: 3 to 3.5 - Elevation 12",
      },
    ],
  },

  {
    day: "Day 5",
    variations: "Back / Chest + Biceps",
    exercises: [
      {
        id: "d5-1",
        name: "Plate-Loaded Low Row",
        equipment: "Machine",
        setType: "Drop Set",
        sets: 2,
        reps: "8–12",
        rest: 180,
        notes: "Top set → back-off → drop to failure.",
      },
      {
        id: "d5-2",
        name: "Single-Arm Cable Lat Pulldown",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes: "Drive to hip.",
      },
      {
        id: "d5-3",
        name: "Seated Cable Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–12",
        rest: 120,
        notes: "Chest tall.",
      },
      {
        id: "d5-4",
        name: "Cable Seated Chest Press",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 120,
        notes: "Downward path.",
      },
      {
        id: "d5-5",
        name: "Dumbbell Incline Bench Press",
        equipment: "Dumbbells",
        setType: "Cluster Back-Off",
        sets: 2,
        reps: "8–10",
        rest: 180,
        notes: "6×3 cluster.",
      },
      {
        id: "d5-6",
        name: "Lying Plate-Loaded Chest Press",
        equipment: "Machine",
        setType: "Top + Back-Off",
        sets: 3,
        reps: "8–10",
        rest: 180,
        notes: "2 top sets, 1 back-off.",
      },
      {
        id: "d5-7",
        name: "Cable Preacher Curl",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15, 12",
        rest: 60,
        notes: "Peak squeeze.",
      },
    ],
  },

  {
    day: "Day 6",
    variations: "Shoulders / Triceps / Biceps",
    exercises: [
      {
        id: "d6-1",
        name: "Seated Lateral Raise",
        equipment: "Machine",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 120,
        notes: "Last set double drop.",
      },
      {
        id: "d6-2",
        name: "Plate-Loaded Shoulder Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "8–10",
        rest: 180,
        notes: "",
      },
      {
        id: "d6-3",
        name: "Seated DB Lateral Raise",
        equipment: "Dumbbells",
        setType: "Drop Set",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Drop 25% each set.",
      },
      {
        id: "d6-4",
        name: "Cable One-Arm Lateral Raise",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 120,
        notes: "Pinkies up.",
      },
      {
        id: "d6-5",
        name: "Standing Cable Rear Delt Fly",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "15–20",
        rest: 120,
        notes: "Partial ROM.",
      },
      {
        id: "d6-6",
        name: "Lying Triceps Extension (Skull Crushers)",
        equipment: "EZ Bar",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "",
      },
      {
        id: "d6-7",
        name: "Biceps Curl (21s)",
        equipment: "Barbell / Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "21",
        rest: 120,
        notes: "7 bottom, 7 top, 7 full.",
      },
    ],
  },

  {
    day: "Day 7",
    variations: "Abdominal Routine X Cardio",
    exercises: [
      {
        id: "d7-1",
        name: "Decline Bench Reverse Crunch",
        equipment: "Bench",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
      {
        id: "d7-2",
        name: "90° Hyperextension Sit-Up",
        equipment: "Hyperextension Bench",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
      {
        id: "d7-3",
        name: "Seated Crunch Machine",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "",
      },
      {
        id: "d7-4",
        name: "Incline Walk",
        equipment: "treadmill",
        setType: "steady State",
        sets: "30 mins",
        reps: "_",
        rest: 0,
        notes: "Speed: 3 to 3.5 - Elevation 12",
      },
    ],
  },
];

export const womensBeginnerWorkoutDays: WorkoutDay[] = [
  // ======================
  // DAY 1 – Glutes & Legs
  // ======================
  {
    day: "Day 1",
    variations: "Glutes & Legs",
    link: "https://link.strong.app/ulxizcyh",
    exercises: [
      {
        id: "bw1-1",
        name: "Hip Thrust",
        equipment: "Barbell / Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Pause 1 sec at top, squeeze glutes.",
      },
      {
        id: "bw1-2",
        name: "Leg Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12",
        rest: 120,
        notes: "Feet slightly higher to emphasize glutes.",
      },
      {
        id: "bw1-3",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 90,
        notes: "Controlled tempo, squeeze hamstrings.",
      },
      {
        id: "bw1-4",
        name: "Goblet Squat",
        equipment: "Dumbbell",
        setType: "Straight",
        sets: 3,
        reps: "10",
        rest: 90,
        notes: "Sit back, chest tall.",
      },
      {
        id: "bw1-5",
        name: "Walking Lunges",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "10 / leg",
        rest: 120,
        notes: "Short stride, controlled movement.",
      },
      {
        id: "bw1-6",
        name: "Standing Calf Raise",
        equipment: "Machine / Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Full stretch and squeeze.",
      },
    ],
  },

  // ======================
  // DAY 2 – Upper Body (Back + Arms)
  // ======================
  {
    day: "Day 2",
    variations: "Upper Body (Back + Arms)",
    link: "https://link.strong.app/vbawwsiz",
    exercises: [
      {
        id: "bw2-1",
        name: "Lat Pulldown",
        equipment: "Cable / Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Pull elbows down, chest tall.",
      },
      {
        id: "bw2-2",
        name: "Seated Cable Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 90,
        notes: "Squeeze shoulder blades together.",
      },
      {
        id: "bw2-3",
        name: "Assisted Pull-Up",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "8–10",
        rest: 120,
        notes: "Controlled reps, full stretch.",
      },
      {
        id: "bw2-4",
        name: "Dumbbell Shoulder Press",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Stop 1–2 reps before failure.",
      },
      {
        id: "bw2-5",
        name: "Cable Triceps Pushdown",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Elbows pinned to sides.",
      },
      {
        id: "bw2-6",
        name: "Dumbbell Hammer Curl",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Neutral grip, controlled tempo.",
      },
    ],
  },

  // ======================
  // DAY 3 – Glutes, Hamstrings & Core
  // ======================
  {
    day: "Day 3",
    variations: "Glutes / Hamstrings + Core",
    link: "https://link.strong.app/xkgghdaq",
    exercises: [
      {
        id: "bw3-1",
        name: "Romanian Deadlift",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Feel hamstring stretch, neutral spine.",
      },
      {
        id: "bw3-2",
        name: "Hip Abduction",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "15",
        rest: 60,
        notes: "Controlled tempo, glute focus.",
      },
      {
        id: "bw3-3",
        name: "Step-Ups",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "10 / leg",
        rest: 90,
        notes: "Knee aligned with toes.",
      },
      {
        id: "bw3-4",
        name: "Cable Kickbacks",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Squeeze glutes at top.",
      },
      {
        id: "bw3-5",
        name: "Plank",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "30–45 sec",
        rest: 60,
        notes: "Neutral spine, core tight.",
      },
      {
        id: "bw3-6",
        name: "Dead Bug",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "10 / side",
        rest: 60,
        notes: "Slow, controlled core movement.",
      },
    ],
  },

  // ======================
  // DAY 4 – Upper Body + Core
  // ======================
  {
    day: "Day 4",
    variations: "Upper Body + Core",
    link: "https://link.strong.app/hrsaipaw",
    exercises: [
      {
        id: "bw4-1",
        name: "Chest Press",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 120,
        notes: "Controlled negative, no bouncing.",
      },
      {
        id: "bw4-2",
        name: "Pec Deck Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Light weight, stretch & squeeze.",
      },
      {
        id: "bw4-3",
        name: "Face Pull",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "15",
        rest: 60,
        notes: "Posture & shoulder health.",
      },
      {
        id: "bw4-4",
        name: "Seated Lateral Raise",
        equipment: "Dumbbells / Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "No trap engagement.",
      },
      {
        id: "bw4-5",
        name: "Cable Crunch",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Slow, controlled reps.",
      },
      {
        id: "bw4-6",
        name: "Side Plank",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 2,
        reps: "20–30 sec / side",
        rest: 60,
        notes: "Core stability focus.",
      },
    ],
  },
];

export const womensIntermediateWorkoutDays: WorkoutDay[] = [
  {
    day: "Day 1",
    variations: "Quads and Arms",
    exercises: [
      {
        id: "iw1-1",
        name: "Barbell Hip Thrust",
        equipment: "Barbell / Machine",
        setType: "Straight",
        sets: 4,
        reps: "8–10",
        rest: 150,
        notes: "Pause 1 sec at top, squeeze glutes.",
      },
      {
        id: "iw1-2",
        name: "Hack Squat",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 180,
        notes: "Quad-focused depth, controlled eccentric.",
      },
      {
        id: "iw1-3",
        name: "Leg Press (High Foot)",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 150,
        notes: "Glute bias, constant tension.",
      },
      {
        id: "iw1-4",
        name: "Bulgarian Split Squat",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "8 / leg",
        rest: 120,
        notes: "Slow eccentric, knee stable.",
      },
      {
        id: "iw1-5",
        name: "Leg Extension",
        equipment: "Machine",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 90,
        notes: "Controlled, no swinging.",
      },
      {
        id: "iw1-6",
        name: "Standing Calf Raise",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Full stretch and squeeze.",
      },
    ],
  },

  // ======================
  // DAY 2 – Upper Body (Back + Shoulders)
  // ======================
  {
    day: "Day 2",
    variations: "Back / Shoulders",
    exercises: [
      {
        id: "iw2-1",
        name: "Assisted Pull-Up / Lat Pulldown",
        equipment: "Machine",
        setType: "Straight",
        sets: 4,
        reps: "8–10",
        rest: 120,
        notes: "Full stretch, chest tall.",
      },
      {
        id: "iw2-2",
        name: "Chest-Supported Row",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Elbow-driven pull.",
      },
      {
        id: "iw2-3",
        name: "Seated Shoulder Press",
        equipment: "Dumbbells / Machine",
        setType: "Straight",
        sets: 3,
        reps: "8–10",
        rest: 150,
        notes: "Stop 1 rep before failure.",
      },
      {
        id: "iw2-4",
        name: "Seated Lateral Raise",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 90,
        notes: "No trap engagement.",
      },
      {
        id: "iw2-5",
        name: "Face Pull",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "15",
        rest: 60,
        notes: "Rear delts & posture.",
      },
      {
        id: "iw2-6",
        name: "Dumbbell Curl",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Controlled tempo.",
      },
    ],
  },

  // ======================
  // DAY 3 – Glutes / Hamstrings
  // ======================
  {
    day: "Day 3",
    variations: "Glutes / Hamstrings",
    exercises: [
      {
        id: "iw3-1",
        name: "Romanian Deadlift",
        equipment: "Barbell / Dumbbells",
        setType: "Straight",
        sets: 4,
        reps: "8–10",
        rest: 180,
        notes: "Hamstring stretch, neutral spine.",
      },
      {
        id: "iw3-2",
        name: "Seated Leg Curl",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Pause at contraction.",
      },
      {
        id: "iw3-3",
        name: "Hip Abduction",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "15–20",
        rest: 60,
        notes: "Glute med focus.",
      },
      {
        id: "iw3-4",
        name: "Step-Ups",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "10 / leg",
        rest: 120,
        notes: "Knee aligned with toes.",
      },
      {
        id: "iw3-5",
        name: "Cable Kickbacks",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "15",
        rest: 60,
        notes: "Peak glute squeeze.",
      },
      {
        id: "iw3-6",
        name: "Stability Ball Leg Curl",
        equipment: "Stability Ball",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Hamstring control.",
      },
    ],
  },

  // ======================
  // DAY 4 – Core & Conditioning
  // ======================
  {
    day: "Day 4",
    variations: "Core & Conditioning",
    exercises: [
      {
        id: "iw4-1",
        name: "Plank",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "45–60 sec",
        rest: 60,
        notes: "Neutral spine.",
      },
      {
        id: "iw4-2",
        name: "Hanging Knee Raise",
        equipment: "Bar / Bench",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Controlled reps.",
      },
      {
        id: "iw4-3",
        name: "Cable Crunch",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Slow tempo.",
      },
      {
        id: "iw4-4",
        name: "Back Extension",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Glutes + lower back.",
      },
      {
        id: "iw4-5",
        name: "Incline Walk / Bike",
        equipment: "Cardio Machine/ treadmill",
        setType: "Steady State",
        sets: "10–15 min",
        reps: "—",
        rest: 0,
        notes: "Speed: 2.5 to 3.5 - Elevation 12",
      },
    ],
  },

  // ======================
  // DAY 5 – Upper Body (Chest + Arms)
  // ======================
  {
    day: "Day 5",
    variations: "Chest / Arms",
    exercises: [
      {
        id: "iw5-1",
        name: "Incline Dumbbell Press",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 4,
        reps: "8–10",
        rest: 150,
        notes: "Controlled depth.",
      },
      {
        id: "iw5-2",
        name: "Chest Press Machine",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 120,
        notes: "Smooth reps.",
      },
      {
        id: "iw5-3",
        name: "Pec Deck Fly",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 90,
        notes: "Stretch & squeeze.",
      },
      {
        id: "iw5-4",
        name: "Cable Triceps Pushdown",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 60,
        notes: "Elbows pinned.",
      },
      {
        id: "iw5-5",
        name: "Overhead Triceps Extension",
        equipment: "Cable",
        setType: "Straight",
        sets: 2,
        reps: "12–15",
        rest: 60,
        notes: "Long head focus.",
      },
      {
        id: "iw5-6",
        name: "Hammer Curl",
        equipment: "Dumbbells",
        setType: "Straight",
        sets: 3,
        reps: "12",
        rest: 60,
        notes: "Neutral grip.",
      },
    ],
  },

  // ======================
  // DAY 6 – Glutes (Pump / Shape)
  // ======================
  {
    day: "Day 6",
    variations: "Glutes (Pump / Shape)",
    exercises: [
      {
        id: "iw6-1",
        name: "Hip Thrust (Light)",
        equipment: "Barbell / Machine",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 120,
        notes: "Constant tension.",
      },
      {
        id: "iw6-2",
        name: "Smith Squat (Glute Bias)",
        equipment: "Smith Machine",
        setType: "Straight",
        sets: 3,
        reps: "10–12",
        rest: 150,
        notes: "Sit back, glute focus.",
      },
      {
        id: "iw6-3",
        name: "Cable Pull-Through",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12–15",
        rest: 90,
        notes: "Hip hinge pattern.",
      },
      {
        id: "iw6-4",
        name: "Frog Pumps",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "20",
        rest: 45,
        notes: "Burnout set.",
      },
      {
        id: "iw6-5",
        name: "Banded Lateral Walk",
        equipment: "Resistance Band",
        setType: "Straight",
        sets: 3,
        reps: "20 steps",
        rest: 45,
        notes: "Glute med activation.",
      },
      {
        id: "iw6-6",
        name: "Seated Calf Raise",
        equipment: "Machine",
        setType: "Straight",
        sets: 3,
        reps: "15",
        rest: 60,
        notes: "Controlled.",
      },
    ],
  },

  // ======================
  // DAY 7 – Abs & Mobility
  // ======================
  {
    day: "Day 7",
    variations: "Abs & Mobility",
    exercises: [
      {
        id: "iw7-1",
        name: "Decline Bench Reverse Crunch",
        equipment: "Bench",
        setType: "Straight",
        sets: 4,
        reps: "12–15",
        rest: 60,
        notes: "Controlled reps.",
      },
      {
        id: "iw7-2",
        name: "Cable Woodchopper",
        equipment: "Cable",
        setType: "Straight",
        sets: 3,
        reps: "12 / side",
        rest: 60,
        notes: "Oblique focus.",
      },
      {
        id: "iw7-3",
        name: "Dead Bug",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 3,
        reps: "10 / side",
        rest: 60,
        notes: "Core control.",
      },
      {
        id: "iw7-4",
        name: "Side Plank",
        equipment: "Bodyweight",
        setType: "Straight",
        sets: 2,
        reps: "30 sec / side",
        rest: 60,
        notes: "Stability.",
      },
      {
        id: "iw7-5",
        name: "Mobility Flow",
        equipment: "Bodyweight",
        setType: "Mobility",
        sets: "10 min",
        reps: "—",
        rest: 0,
        notes: "Hips, spine, recovery.",
      },
    ],
  },
];
